import { Injectable } from "@nestjs/common";
import { slonik } from "../config";
import { DatabaseConnection, QueryResult, sql } from "slonik";

@Injectable()
export class TestService {
  async testDb(): Promise<QueryResult<queries.User>> {
    return (await slonik).connect(async (connection: DatabaseConnection) => {
      const result = await connection.query(
        sql<queries.User>`select name from users where user_id = 1`
      );
      connection.any;
      console.log(result);
      // return JSON.stringify(result.rows[0].name);
      return await result;
    });
  }
}

export declare namespace queries {
  // Generated by @slonik/typegen

  /** - query: `select name from users where user_id = 1` */
  export interface User {
    /** column: `public.users.name`, not null: `true`, regtype: `character varying(50)` */
    name: string;
  }
}
